services:
  - type: web
    name: el-plan
    plan: free
    env: docker
    dockerfilePath: Dockerfile
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: DEBUG
        value: "False"
      - key: SECRET_KEY
        generateValue: true
      - key: GEMINI_API_KEY
        value: AIzaSyBSC5OwBUh1v0qJDZM6_tnr_Llhonel07w
      - key: GEMINI_API_KEY_2
        value: AIzaSyBvjw6B71RbtagoFnTygx6nCj6qmb7bPDM
      - key: MONGODB_CONNECTION_STRING
        value: mongodb+srv://Z33xD:MxVEi2OTvIs4HfjM@el-plan-stem.12pthvy.mongodb.net/?retryWrites=true&w=majority&appName=El-Plan-STEM
