services:
  - type: web
    name: el-plan
    plan: free
    runtime: python
    workingDirectory: backend
    envVars:
      - fromGroup: el-plan-env
      - key: ALLOWED_HOSTS
        value: "el-plan.onrender.com"
      - key: PORT
        value: "10000"
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
    startCommand: gunicorn backend.wsgi:application --bind 0.0.0.0:${PORT}
    healthCheckPath: "/"
databases: []
