services:
  - type: web
    name: el-plan
    env: python
    plan: free
    buildCommand: |
      pip install --upgrade pip
      pip install -r requirements.txt
      cd backend
      python manage.py collectstatic --noinput
      python manage.py migrate --noinput
    startCommand: gunicorn backend.wsgi:application
    envVars:
      - key: DJANGO_SETTINGS_MODULE
        value: backend.settings
      - key: SECRET_KEY
        generateValue: true
      - key: DEBUG
        value: "False"
      - key: GEMINI_API_KEY
        value: AIzaSyBSC5OwBUh1v0qJDZM6_tnr_Llhonel07w
      - key: GEMINI_API_KEY_2
        value: AIzaSyBvjw6B71RbtagoFnTygx6nCj6qmb7bPDM
      - key: MONGODB_CONNECTION_STRING
        value: "mongodb+srv://Z33xD:MxVEi2OTvIs4HfjM@el-plan-stem.12pthvy.mongodb.net/?retryWrites=true&w=majority&appName=El-Plan-STEM"
